---
- name: Run old fasioned oc CLI commands
  block:
  - name: Log into the cluster
    shell:
      cmd: "oc login {{ cluster_api_url }} --password=\"{{ cluster_kubeadmin_password }}\" --username=\"{{ cluster_kubeadmin_username }}\" --insecure-skip-tls-verify=true"
    no_log: true
    register: cluster_auth_status
    until: (cluster_auth_status.rc == 0)
    retries: 120
    delay: 20

  - name: Deploy Extra Defined Roles
    include_role:
      name: "{{ role_name }}"
    loop: "{{ extra_roles }}"
    loop_control:
      loop_var: role_name
    when: extra_roles is defined

  always:
  - name: Log out of the cluster
    shell:
      cmd: oc logout

  tags:
  - post_tasks_4
