---
# tasks file for ocp4-ntp-configuration
- name: Set NTP Sources as MachineConfigs
  when: ntp_sources is defined
  block:
  - name: Create the MachineConfig for the Control Nodes NTP chrony Configuration
    kubernetes.core.k8s:
      state: present
      merge_type:
      - strategic-merge
      - merge
      definition:
        apiVersion: machineconfiguration.openshift.io/v1
        kind: MachineConfig
        metadata:
          name: 99-masters-chrony-configuration
          labels:
            machineconfiguration.openshift.io/role: master
        spec:
          config:
            ignition:
              config: {}
              security:
                tls: {}
              timeouts: {}
              version: 3.2.0
            networkd: {}
            passwd: {}
            storage:
              files:
              - contents:
                  source: "data:text/plain;charset=utf-8;base64,{{ lookup('template', 'chronyc.conf.j2') | b64encode }}"
                mode: 420 
                overwrite: true
                path: /etc/chrony.conf
          osImageURL: ""

  - name: Create the MachineConfig for the Application Nodes NTP chrony Configuration
    kubernetes.core.k8s:
      state: present
      merge_type:
      - strategic-merge
      - merge
      definition:
        apiVersion: machineconfiguration.openshift.io/v1
        kind: MachineConfig
        metadata:
          name: 99-workers-chrony-configuration
          labels:
            machineconfiguration.openshift.io/role: worker
        spec:
          config:
            ignition:
              config: {}
              security:
                tls: {}
              timeouts: {}
              version: 3.2.0
            networkd: {}
            passwd: {}
            storage:
              files:
              - contents:
                  source: "data:text/plain;charset=utf-8;base64,{{ lookup('template', 'chronyc.conf.j2') | b64encode }}"
                mode: 420 
                overwrite: true
                path: /etc/chrony.conf
          osImageURL: ""