---
################################################## SSH Key Configuration
# generate_ssh_key: true/false, will generate unique key pair if true
generate_ssh_key: true
# ssh_pub_key_path: If 'generate_ssh_key' is false, point to an existing SSH Public Key
ssh_pub_key_path: "~/.ssh/id_rsa.pub"

################################################## OpenShift Pull Secret
# pull_secret: Often best to pull from a file outside of the repo - get it from here: https://cloud.redhat.com/openshift/install/pull-secret
pull_secret: "{{ lookup('file', '~/pull-secret.txt') | to_json }}"

################################################## Cluster Basics
# cluster_type: Standard (HA CP+App Nodes), SNO (Single Node OpenShift)
cluster_type: Standard

# cluster_name and cluster_domain will form the cluster base endpoint, eg cluster_name.cluster_domain
# Ensure the DNS A records for {api,api-int,apps,*.apps}.cluster_name.cluster_domain exist
cluster_name: play-ocp
cluster_domain: kemo.labs

cluster_version: 4.7.9
cluster_image: quay.io/openshift-release-dev/ocp-release:4.7.9-x86_64

################################################## Cluster Networking
# cluster_network_type = Default, Cillium, or Calico
cluster_network_type: Default
# cluster_api_vip: an IP or "auto"
cluster_api_vip: 192.168.42.74
# cluster_load_balancer_vip: an IP or "auto"
cluster_load_balancer_vip: 192.168.42.75
# cluster_node_cidr: A CIDR definition or "auto"
cluster_node_cidr: 192.168.42.0/24

################################################## Cluster Node IPAM
# cluster_node_network_ipam: dhcp or static
cluster_node_network_ipam: static
######################### If cluster_node_network_ipam == static:
cluster_node_network_static_dns_servers:
  - 192.168.42.9
  - 192.168.42.10
cluster_node_network_static_dns_search_domains:
  - kemo.labs
cluster_nodes:
  - name: cp-1
    type: control-plane
    vm:
      disk_size: 60
      cpu_cores: 4
      cpu_sockets: 1
      cpu_threads: 1
      memory: 16384
    interfaces:
      - name: eth0
        mac_address: 54:52:00:42:69:01
        dhcp: false
        ipv4:
          - address: 192.168.42.80
            prefix: 24
        routes:
          - destination: 0.0.0.0/0
            next_hop_address: 192.168.42.1
            next_hop_interface: eth0
            table_id: 254
  - name: cp-2
    type: control-plane
    vm:
      disk_size: 60
      cpu_cores: 4
      cpu_sockets: 1
      cpu_threads: 1
      memory: 16384
    interfaces:
      - name: eth0
        mac_address: 54:52:00:42:69:02
        dhcp: false
        ipv4:
          - address: 192.168.42.81
            prefix: 24
        routes:
          - destination: 0.0.0.0/0
            next_hop_address: 192.168.42.1
            next_hop_interface: eth0
            table_id: 254
  - name: cp-3
    type: control-plane
    vm:
      disk_size: 60
      cpu_cores: 4
      cpu_sockets: 1
      cpu_threads: 1
      memory: 16384
    interfaces:
      - name: eth0
        mac_address: 54:52:00:42:69:03
        dhcp: false
        ipv4:
          - address: 192.168.42.82
            prefix: 24
        routes:
          - destination: 0.0.0.0/0
            next_hop_address: 192.168.42.1
            next_hop_interface: eth0
            table_id: 254
  - name: app-1
    type: application-node
    vm:
      disk_size: 60
      cpu_cores: 4
      cpu_sockets: 1
      cpu_threads: 1
      memory: 32768
    interfaces:
      - name: eth0
        mac_address: 54:52:00:42:69:04
        dhcp: false
        ipv4:
          - address: 192.168.42.83
            prefix: 24
        routes:
          - destination: 0.0.0.0/0
            next_hop_address: 192.168.42.1
            next_hop_interface: eth0
            table_id: 254
  - name: app-2
    type: application-node
    vm:
      disk_size: 60
      cpu_cores: 4
      cpu_sockets: 1
      cpu_threads: 1
      memory: 32768
    interfaces:
      - name: eth0
        mac_address: 54:52:00:42:69:05
        dhcp: false
        ipv4:
          - address: 192.168.42.84
            prefix: 24
        routes:
          - destination: 0.0.0.0/0
            next_hop_address: 192.168.42.1
            next_hop_interface: eth0
            table_id: 254
  - name: app-3
    type: application-node
    vm:
      disk_size: 60
      cpu_cores: 4
      cpu_sockets: 1
      cpu_threads: 1
      memory: 32768
    interfaces:
      - name: eth0
        mac_address: 54:52:00:42:69:06
        dhcp: false
        ipv4:
          - address: 192.168.42.85
            prefix: 24
        routes:
          - destination: 0.0.0.0/0
            next_hop_address: 192.168.42.1
            next_hop_interface: eth0
            table_id: 254

################################################## DO NOT EDIT PAST THIS LINE (unless you know what you're doing)
cluster_network_cidr: 10.128.0.0/14
cluster_network_host_prefix: 23
cluster_service_cidr: 172.30.0.0/16

generated_asset_directory: ./.generated
