---
- name: Set Calico Networking Cluster Preconfig
  uri:
    url: "{{ assisted_service_endpoint }}/clusters/{{ cluster_id }}/install-config"
    return_content: yes
    method: PATCH
    body: '{"networking":{"networkType":"Calico"}}'
    status_code: 201
    body_format: json
    headers:
      Content-Type: application/json
  register: set_cluster_preconfig_networking_calico
  when: cluster_network_type == "Calico"

- name: Set NMState Cluster Preconfig
  set_fact:
    static_networking_preconfig: "{{ rendered_template }}"
  vars:
    rendered_template: "{{ lookup('template', 'templates/static_networking_config.json.j2') }}"