---
- name: Ensure the cluster is in a valid state to get ready to install...
  uri:
    url: "{{ assisted_service_endpoint }}/clusters/{{ cluster_id }}"
    return_content: yes
    method: GET
    status_code: 200
    body_format: json
    headers:
      Content-Type: application/json
  register: cluster_current_status

- name: Start the Installation of the OpenShift Cluster
  uri:
    url: "{{ assisted_service_endpoint }}/clusters/{{ cluster_id }}/actions/install"
    return_content: yes
    method: POST
    status_code: 202
    body_format: json
    headers:
      Content-Type: application/json
  when: cluster_current_status.json.status == "ready"