---
- name: Change password the old fashioned way
  block:
  - name: set fact
    set_fact:
      passwordHash: "{{ core_user_password | password_hash('sha512') }}"

  - name: Template the bash script over
    template:
      src: templates/core_user_password.sh.j2
      dest: "{{ generated_asset_directory + '/' + cluster_id + '/core_user_password.sh' }}"
      mode: 0775

  - name: Run the bash script
    shell: |
      sh "{{ generated_asset_directory + '/' + cluster_id + '/core_user_password.sh' }}"
    register: cmd_res

  - name: Fail on output
    fail:
      msg: 
        - Failed! Unexpected result from bash script!
        - "{{ cmd_res }}"
    when: cmd_res.stdout != "FINISHED"

  - name: Delete template
    file:
      path: "{{ generated_asset_directory + '/' + cluster_id + '/core_user_password.sh' }}"
      state: absent