---
- name: Set appropriate next steps
  set_fact:
    invalid_next_steps:
      - error
      - installing
      - finalizing
      - installed
      - adding-hosts
      - cancelled
      - installing-pending-user-action

- name: Ensure the cluster is in a valid state to get ready to install...
  uri:
    headers: "{{ compiled_uri_headers }}"
    url: "{{ assisted_service_endpoint }}/clusters/{{ cluster_id }}"
    return_content: yes
    method: GET
    status_code: 200
    body_format: json
  register: cluster_current_status

- name: Ensure the cluster is ready to install
  uri:
    headers: "{{ compiled_uri_headers }}"
    url: "{{ assisted_service_endpoint }}/clusters/{{ cluster_id }}"
    return_content: yes
    method: GET
    status_code: 200
    body_format: json
  register: cluster_install_status
  until: (cluster_install_status.json.status == "ready")
  retries: 60
  delay: 15
  when: cluster_current_status.json.status not in invalid_next_steps