---
- name: Combine no proxy list
  set_fact:
    cluster_ntp_sources: "{{ ntp_sources | join(',') }}"

- name: Set body data
  set_fact:
    override_ntp_ic_body: "{ \"additional_ntp_sources\": \"{{ cluster_ntp_sources|default('0.pool.ntp.org') }}\" }"

- name: Inject NTP config into the InfraEnv
  uri:
    headers: "{{ compiled_uri_headers }}"
    url: "{{ assisted_service_endpoint }}/infra-envs/{{ infraenv_id }}"
    return_content: yes
    method: PATCH
    body:  '{{ override_ntp_ic_body }}'
    status_code: 201
    body_format: json
  register: ntpInfraEnv_resp
