---

- name: Set override string
  set_fact:
    ignition_config_override_files: "{{ ignition_config_override_files | default('') }}{{ ',' if ignition_config_override_files is defined and ignition_config_override_files != '' }}{{ '{\"path\": \"/etc/pki/ca-trust/source/anchors/extra_ca.pem\", \"mode\": 420, \"overwrite\": true, \"user\": { \"name\": \"root\"},\"contents\": {\"source\": \"data:text/plain;base64,{{ additionalTrustBundles | b64encode }}\"}}' }}"

#- name: debug ignition_config_override_files
#  debug:
#    msg: "{{ ignition_config_override_files }}"

- name: Set body data
  set_fact:
    #override_body: "{ \"ignition_config_override\": '{{ ignition_config_override_bundle_string | to_json }}{{ ',' if ignition_config_overrides_resp.json.ignition_config_override != '' }}{{ ignition_config_overrides_resp.json.ignition_config_override }}' }"
    override_ic_body: "{ \"additionalTrustBundle\": {{ additionalTrustBundles | to_json }} }"

#- name: Inject extra Root CAs into the Discovery ISO
#  uri:
#    headers: "{{ compiled_uri_headers }}"
#    url: "{{ assisted_service_endpoint }}/infra-envs/{{ infraenv_id }}"
#    return_content: yes
#    method: PATCH
#    body:  "{{ override_body }}"
#    status_code: 201
#    body_format: json
#  register: additionalBundle_resp

#- name: d
#  debug:
#    msg: "{{ additionalBundle_resp }}"

- name: Inject extra Root CAs into the install-config.yaml
  uri:
    headers: "{{ compiled_uri_headers }}"
    url: "{{ assisted_service_endpoint }}/clusters/{{ cluster_id }}/install-config"
    return_content: yes
    method: PATCH
    body:  '{{ override_ic_body | to_json }}'
    status_code: 201
    body_format: json
  register: additionalBundleIC_resp