---
- name: Template Libvirt VM XML files for debug purposes
  template:
    src: templates/kvm_libvirt_vm.xml.j2
    dest: "{{ generated_asset_directory }}/{{ cluster_id }}/kvm_vm.{{ item.name }}.xml"
  loop: "{{ cluster_nodes }}"
  loop_control:
    label: "{{ item.name }}"

- name: Create OpenShift VMs on Libvirt Host
  community.libvirt.virt:
    command: define
    xml: "{{ lookup('template', 'templates/kvm_libvirt_vm.xml.j2') }}"
    uri: "{{ libvirt_uri }}"
  loop: "{{ cluster_nodes }}"
  loop_control:
    label: "{{ item.name }}"

- name: Boot the OpenShift VMs
  community.libvirt.virt:
    name: "{{ cluster_name }}-{{ item.name }}"
    state: running
    uri: "{{ libvirt_uri }}"
  loop: "{{ cluster_nodes }}"
  loop_control:
    label: "{{ item.name }}"