---

- name: Get Running VMs
  shell: "virsh list --state-running --name"
  register: running_vm_check_cmd

- name: Template Libvirt VM XML files for debug purposes
  template:
    src: templates/kvm_libvirt_vm.xml.j2
    dest: "{{ generated_asset_directory }}/{{ cluster_id }}/kvm_vm.{{ node.name }}.xml"
  loop: "{{ cluster_nodes }}"
  loop_control:
    loop_var: node
    label: "{{ node.name }}"

- name: Create OpenShift VMs on Libvirt Host
  community.libvirt.virt:
    command: define
    xml: "{{ lookup('template', 'templates/kvm_libvirt_vm.xml.j2') }}"
    uri: "{{ libvirt_uri }}"
  loop: "{{ cluster_nodes }}"
  loop_control:
    loop_var: node
    label: "{{ node.name }}"
  when: (cluster_name + '-' + node.name) not in running_vm_check_cmd.stdout_lines

- name: Boot the OpenShift VMs
  community.libvirt.virt:
    name: "{{ cluster_name }}-{{ node.name }}"
    state: running
    uri: "{{ libvirt_uri }}"
  loop: "{{ cluster_nodes }}"
  loop_control:
    loop_var: node
    label: "{{ node.name }}"
  when: (cluster_name + '-' + node.name) not in running_vm_check_cmd.stdout_lines