---
kind: ConfigMap
apiVersion: v1
metadata:
  name: kubernetes-services-endpoint
  namespace: tigera-operator
data:
  KUBERNETES_SERVICE_HOST: "{{ cluster_api_vip }}"
  KUBERNETES_SERVICE_PORT: "6443"