---
- name: Create OpenShift Objects for Elastic
  k8s:
    state: present
    merge_type:
    - strategic-merge
    - merge
    definition: "{{ lookup('file', item ) | from_yaml }}"
  loop:
  - ./files/elastic_subscription.yaml

- name: Wait for Elastic CRD
  k8s_info:
    api_version: apiextensions.k8s.io/v1beta1
    kind: CustomResourceDefinition
    name: elasticsearches.logging.openshift.io
  register: r_elastic_crd
  retries: 200
  delay: 10
  until: r_elastic_crd.resources | list | length == 1

- name: Notify user if Elastic deployment failed
  when: not r_elastic_crd.resources | list | length == 1
  debug:
    msg: "user.info: *** Elastic could not be installed ***"